# A string used as the project reference
project_id = "qezunutqfumuzloarrti"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
verify_jwt = false
name = "generate-medical-certificate"

[[functions]]
verify_jwt = false
name = "generate-receipt"