// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qezunutqfumuzloarrti.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlenVudXRxZnVtdXpsb2FycnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI1MDU1OTEsImV4cCI6MjA0ODA4MTU5MX0.Wr5BdtJE31JWVV5ZrnvQx3Kfb1Bq_tauMWrpfMHa_tU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);